Fix Windows build: rename TokenType to LamoTokenType
The Windows SDK's winnt.h (pulled in via <windows.h>) defines TokenType
as an enumerator inside enum _TOKEN_INFORMATION_CLASS. Our lexer.h also
defined TokenType as a typedef, causing a redeclaration error on
mingw-gcc:

  src/lexer/lexer.h:29:3: error: 'TokenType' redeclared as different kind of symbol

Renaming our TokenType to LamoTokenType across all source files (lexer.h,
lexer.c, ast.h, ast.c, parser.c, codegen.c, lamo_v2.c) eliminates the
collision. Also define WIN32_LEAN_AND_MEAN and NOGDI before <windows.h>
in lamo_v2.c to keep the windows.h surface small.